# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: PMRM_Service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'PMRM_Service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12PMRM_Service.proto\"7\n\x13\x43reateRecordRequest\x12\x12\n\npatient_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"9\n\x14\x43reateRecordResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\trecord_id\x18\x02 \x01(\t\"*\n\x15RetrieveRecordRequest\x12\x11\n\trecord_id\x18\x01 \x01(\t\"J\n\x16RetrieveRecordResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\npatient_id\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\":\n\x13UpdateRecordRequest\x12\x11\n\trecord_id\x18\x01 \x01(\t\x12\x10\n\x08new_data\x18\x02 \x01(\t\"9\n\x14UpdateRecordResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\trecord_id\x18\x02 \x01(\t\"(\n\x13\x44\x65leteRecordRequest\x12\x11\n\trecord_id\x18\x01 \x01(\t\"9\n\x14\x44\x65leteRecordResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x11\n\trecord_id\x18\x02 \x01(\t2\x90\x02\n\x14MedicalRecordService\x12;\n\x0c\x43reateRecord\x12\x14.CreateRecordRequest\x1a\x15.CreateRecordResponse\x12\x41\n\x0eRetrieveRecord\x12\x16.RetrieveRecordRequest\x1a\x17.RetrieveRecordResponse\x12;\n\x0cUpdateRecord\x12\x14.UpdateRecordRequest\x1a\x15.UpdateRecordResponse\x12;\n\x0c\x44\x65leteRecord\x12\x14.DeleteRecordRequest\x1a\x15.DeleteRecordResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'PMRM_Service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATERECORDREQUEST']._serialized_start=22
  _globals['_CREATERECORDREQUEST']._serialized_end=77
  _globals['_CREATERECORDRESPONSE']._serialized_start=79
  _globals['_CREATERECORDRESPONSE']._serialized_end=136
  _globals['_RETRIEVERECORDREQUEST']._serialized_start=138
  _globals['_RETRIEVERECORDREQUEST']._serialized_end=180
  _globals['_RETRIEVERECORDRESPONSE']._serialized_start=182
  _globals['_RETRIEVERECORDRESPONSE']._serialized_end=256
  _globals['_UPDATERECORDREQUEST']._serialized_start=258
  _globals['_UPDATERECORDREQUEST']._serialized_end=316
  _globals['_UPDATERECORDRESPONSE']._serialized_start=318
  _globals['_UPDATERECORDRESPONSE']._serialized_end=375
  _globals['_DELETERECORDREQUEST']._serialized_start=377
  _globals['_DELETERECORDREQUEST']._serialized_end=417
  _globals['_DELETERECORDRESPONSE']._serialized_start=419
  _globals['_DELETERECORDRESPONSE']._serialized_end=476
  _globals['_MEDICALRECORDSERVICE']._serialized_start=479
  _globals['_MEDICALRECORDSERVICE']._serialized_end=751
# @@protoc_insertion_point(module_scope)
