# Generated by Django 5.1.3 on 2024-11-15 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('nat_id', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ORG',
            fields=[
                ('org_no', models.AutoField(primary_key=True, serialize=False)),
                ('org_name', models.CharField(max_length=150)),
                ('opening_details', models.CharField(max_length=300)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbms_service.user')),
                ('specialty', models.CharField(blank=True, max_length=250, null=True)),
                ('sub_specialty', models.CharField(blank=True, max_length=250, null=True)),
            ],
            bases=('dbms_service.user',),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dbms_service.user')),
                ('street', models.CharField(blank=True, max_length=250, null=True)),
                ('region', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=3, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            bases=('dbms_service.user',),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_prescription', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='prescriptions', to='dbms_service.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='dbms_service.patient')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalTest',
            fields=[
                ('test_id', models.AutoField(primary_key=True, serialize=False)),
                ('test_type', models.CharField(blank=True, max_length=15, null=True)),
                ('subject_of_test', models.CharField(blank=True, max_length=50, null=True)),
                ('result', models.CharField(blank=True, max_length=100, null=True)),
                ('image_of_scan', models.CharField(blank=True, max_length=50, null=True)),
                ('date_time_of_upload', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_tests', to='dbms_service.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('app_id', models.AutoField(primary_key=True, serialize=False)),
                ('app_date_time', models.DateTimeField(blank=True, null=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='dbms_service.org')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='appointments', to='dbms_service.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='dbms_service.patient')),
            ],
        ),
        migrations.CreateModel(
            name='ORGLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=250)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='dbms_service.org')),
            ],
            options={
                'unique_together': {('org', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=35)),
                ('subscription_heading', models.CharField(blank=True, max_length=2, null=True)),
                ('form_of_intake', models.CharField(blank=True, max_length=25, null=True)),
                ('duration_of_intake', models.IntegerField(blank=True, null=True)),
                ('frequency_of_intake', models.CharField(blank=True, max_length=25, null=True)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='dbms_service.prescription')),
            ],
            options={
                'unique_together': {('prescription', 'medicine_name')},
            },
        ),
        migrations.CreateModel(
            name='DoctorWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_working_days', models.CharField(blank=True, max_length=15, null=True)),
                ('schedule_working_hours', models.CharField(blank=True, max_length=15, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='dbms_service.org')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplaces', to='dbms_service.doctor')),
            ],
            options={
                'unique_together': {('doctor', 'org')},
            },
        ),
        migrations.CreateModel(
            name='TreatmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_patients', to='dbms_service.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_assignments', to='dbms_service.patient')),
            ],
            options={
                'verbose_name': 'Treatment Assignment',
                'verbose_name_plural': 'Treatment Assignments',
                'unique_together': {('patient', 'doctor')},
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referrals_received', to='dbms_service.doctor')),
                ('referring_doctor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referrals_given', to='dbms_service.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='referrals', to='dbms_service.patient')),
            ],
            options={
                'unique_together': {('referring_doctor', 'referred_doctor', 'patient')},
            },
        ),
        migrations.CreateModel(
            name='MedicalCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('med_condition', models.CharField(max_length=14)),
                ('notes', models.CharField(max_length=500)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_conditions', to='dbms_service.patient')),
            ],
            options={
                'unique_together': {('patient', 'med_condition')},
            },
        ),
    ]
