# Generated by Django 5.1.3 on 2024-11-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_service', '0002_remove_patient_city_remove_patient_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='clinic_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
