# Generated by Django 5.1.3 on 2024-11-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_service', '0005_user_id_alter_user_nat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='nat_id',
            field=models.CharField(max_length=14, primary_key=True, serialize=False),
        ),
    ]
