# Generated by Django 5.1.3 on 2024-11-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbms_service', '0003_doctor_clinic_address_doctor_years_of_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
